// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_russian_military_a";
	a[1] = "head_russian_military_c";
	a[2] = "head_russian_military_d";
	a[3] = "head_russian_military_bb";
	a[4] = "head_russian_military_aa";
	a[5] = "head_russian_military_b";
	a[6] = "head_russian_military_e";
	return a;
}
