// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_russian_naval_assault_a";
	a[1] = "body_russian_naval_assault_b";
	a[2] = "body_russian_naval_assault_f";
	a[3] = "body_russian_naval_assault_aa";
	a[4] = "body_russian_naval_assault_bb";
	a[5] = "body_russian_naval_assault_ff";
	return a;
}
