// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "israeli_military_head_b";
	a[1] = "israeli_military_head_b";
	a[2] = "israeli_military_head_b";
	a[3] = "israeli_military_head_b";
	return a;
}
