// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("casual_civ_male_body_c");
	self attach("head_london_male_a", "", true);
	self.headModel = "head_london_male_a";
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("casual_civ_male_body_c");
	precacheModel("head_london_male_a");
}
