// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_yuri_smg_a");
	self attach("head_hero_yuri_a", "", true);
	self.headModel = "head_hero_yuri_a";
	self.voice = "taskforce";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_hero_yuri_smg_a");
	precacheModel("head_hero_yuri_a");
}
