// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_blackice_udt_b");
	self attach("head_hero_grinch_delta", "", true);
	self.headModel = "head_hero_grinch_delta";
	self.voice = "seal";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_hero_blackice_udt_b");
	precacheModel("head_hero_grinch_delta");
}
