// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\alias_test_navy_bodies::main());
	codescripts\character::attachHead( "alias_test_navy_heads", xmodelalias\alias_test_navy_heads::main() );
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\alias_test_navy_bodies::main());
	codescripts\character::precacheModelArray(xmodelalias\alias_test_navy_heads::main());
}
