// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_scientist_b");
	codescripts\character::attachHead( "alias_scientist_heads", xmodelalias\alias_scientist_heads::main() );
	self.voice = "russian";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_scientist_b");
	codescripts\character::precacheModelArray(xmodelalias\alias_scientist_heads::main());
}
