// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("clk_russian_military_body_shotgun_a_duffle");
	self attach("clk_russian_military_disguise_head_c", "", true);
	self.headModel = "clk_russian_military_disguise_head_c";
	self.voice = "delta";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("clk_russian_military_body_shotgun_a_duffle");
	precacheModel("clk_russian_military_disguise_head_c");
}
