// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_scientist_c");
	self.voice = "russian";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("fullbody_scientist_c");
}
