// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_chemwar_russian_assault_e");
	self attach("head_chemwar_russian_b", "", true);
	self.headModel = "head_chemwar_russian_b";
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_chemwar_russian_assault_e");
	precacheModel("head_chemwar_russian_b");
}
