// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_elite_pmc_assault_b");
	self attach("head_russian_military_d_black", "", true);
	self.headModel = "head_russian_military_d_black";
	self.voice = "russian";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_elite_pmc_assault_b");
	precacheModel("head_russian_military_d_black");
}
