// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_blackice_udt");
	self attach("head_russian_naval_b", "", true);
	self.headModel = "head_russian_naval_b";
	self.voice = "seal";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_hero_blackice_udt");
	precacheModel("head_russian_naval_b");
}
