// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_prague_civ_male_drone_e");
	self attach("head_hero_kamarov_a", "", true);
	self.headModel = "head_hero_kamarov_a";
	self.voice = "american";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_prague_civ_male_drone_e");
	precacheModel("head_hero_kamarov_a");
}
