// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_ally_delta_sniper");
	self attach("head_ally_delta_sniper", "", true);
	self.headModel = "head_ally_delta_sniper";
	self.voice = "delta";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_ally_delta_sniper");
	precacheModel("head_ally_delta_sniper");
}
