// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_hazmat_a");
	self.voice = "russian";
	self SetClothType("nylon");
}

precache()
{
	precacheModel("fullbody_hazmat_a");
}
