// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fed_space_assault_body");
	self attach("fed_space_assault_head", "", true);
	self.headModel = "fed_space_assault_head";
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("fed_space_assault_body");
	precacheModel("fed_space_assault_head");
}
