// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_tigershark");
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("fullbody_tigershark");
}
