// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_elite_pmc_assault_b_arctic");
	codescripts\character::attachHead( "alias_elite_pmc_heads", xmodelalias\alias_elite_pmc_heads::main() );
	self.voice = "russian";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_elite_pmc_assault_b_arctic");
	codescripts\character::precacheModelArray(xmodelalias\alias_elite_pmc_heads::main());
}
