// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_price_europe_assault_cc");
	self attach("head_pmc_africa_f", "", true);
	self.headModel = "head_pmc_africa_f";
	self.voice = "seal";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_price_europe_assault_cc");
	precacheModel("head_pmc_africa_f");
}
