// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_ally_sas_sniper");
	self attach("head_ally_sas_sniper", "", true);
	self.headModel = "head_ally_sas_sniper";
	self.voice = "british";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_ally_sas_sniper");
	precacheModel("head_ally_sas_sniper");
}
