// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("israeli_military_body_smg");
	codescripts\character::attachHead( "alias_israeli_military_heads", xmodelalias\alias_israeli_military_heads::main() );
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("israeli_military_body_smg");
	codescripts\character::precacheModelArray(xmodelalias\alias_israeli_military_heads::main());
}
