// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_prototype_deer_a");
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("fullbody_prototype_deer_a");
}
