// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_dubai_male_c_alt");
	self attach("body_vice_president", "", true);
	self.headModel = "body_vice_president";
	self.voice = "russian";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_dubai_male_c_alt");
	precacheModel("body_vice_president");
}
