// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_opforce_africa_militia_sniper");
	self attach("head_opforce_africa_sniper", "", true);
	self.headModel = "head_opforce_africa_sniper";
	self.voice = "african";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_opforce_africa_militia_sniper");
	precacheModel("head_opforce_africa_sniper");
}
