// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_price_europe_assault_cc");
	self attach("head_opforce_henchmen_sniper", "", true);
	self.headModel = "head_opforce_henchmen_sniper";
	self.voice = "seal";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_price_europe_assault_cc");
	precacheModel("head_opforce_henchmen_sniper");
}
