// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_soap_europe_assault_a");
	self.voice = "taskforce";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("fullbody_soap_europe_assault_a");
}
