// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("israeli_military_body_lmg");
	self attach("israeli_military_head_e", "", true);
	self.headModel = "israeli_military_head_e";
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("israeli_military_body_lmg");
	precacheModel("israeli_military_head_e");
}
