// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_ppilot_crew_b");
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("fullbody_ppilot_crew_b");
}
