// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_fso_vest_d");
	self attach("head_fso_e", "", true);
	self.headModel = "head_fso_e";
	self.voice = "russian";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_fso_vest_d");
	precacheModel("head_fso_e");
}
