// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_blackice_udt_b");
	self attach("head_seal_udt_c_iw5", "", true);
	self.headModel = "head_seal_udt_c_iw5";
	self.voice = "seal";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_hero_blackice_udt_b");
	precacheModel("head_seal_udt_c_iw5");
}
