// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_venezuela_army_smg_a");
	self attach("head_makarov_b", "", true);
	self.headModel = "head_makarov_b";
	self.voice = "shadowcompany";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_venezuela_army_smg_a");
	precacheModel("head_makarov_b");
}
