// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\alias_air_crew_bodies::main());
	codescripts\character::attachHead( "alias_air_crew_heads", xmodelalias\alias_air_crew_heads::main() );
	self.voice = "american";
	self SetClothType("cloth");
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\alias_air_crew_bodies::main());
	codescripts\character::precacheModelArray(xmodelalias\alias_air_crew_heads::main());
}
