// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("israeli_military_body_assault");
	self attach("israeli_military_head_c", "", true);
	self.headModel = "israeli_military_head_c";
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("israeli_military_body_assault");
	precacheModel("israeli_military_head_c");
}
