// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_us_rangers_smg_a");
	self attach("head_cnd_test_head_a", "", true);
	self.headModel = "head_cnd_test_head_a";
	self.voice = "delta";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_us_rangers_smg_a");
	precacheModel("head_cnd_test_head_a");
}
