// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_soap_africa_assault_a");
	self.voice = "seal";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("fullbody_soap_africa_assault_a");
}
