// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_opforce_russian_arctic_sniper");
	self attach("head_opforce_russian_arctic_sniper", "", true);
	self.headModel = "head_opforce_russian_arctic_sniper";
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_opforce_russian_arctic_sniper");
	precacheModel("head_opforce_russian_arctic_sniper");
}
