// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("us_space_assault_body");
	self attach("us_space_assault_head", "", true);
	self.headModel = "us_space_assault_head";
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("us_space_assault_body");
	precacheModel("us_space_assault_head");
}
