// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_price_europe_assault_cc");
	self attach("head_hero_sandman_noglasses", "", true);
	self.headModel = "head_hero_sandman_noglasses";
	self.voice = "seal";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_price_europe_assault_cc");
	precacheModel("head_hero_sandman_noglasses");
}
