// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_elite_pmc_assault_b_woodland");
	codescripts\character::attachHead( "alias_russian_military_black_heads", xmodelalias\alias_russian_military_black_heads::main() );
	self.voice = "russian";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_elite_pmc_assault_b_woodland");
	codescripts\character::precacheModelArray(xmodelalias\alias_russian_military_black_heads::main());
}
