// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_soap_africa_assault_a");
	self.voice = "taskforce";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("fullbody_soap_africa_assault_a");
}
