// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_ally_pmc_sniper");
	self.voice = "taskforce";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_ally_pmc_sniper");
}
