// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_delta_elite_snow_lmg_b");
	codescripts\character::attachHead( "alias_delta_elite_heads_longsleeves", xmodelalias\alias_delta_elite_heads_longsleeves::main() );
	self.voice = "delta";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_delta_elite_snow_lmg_b");
	codescripts\character::precacheModelArray(xmodelalias\alias_delta_elite_heads_longsleeves::main());
}
