// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_smg_a_woodland");
	codescripts\character::attachHead( "alias_russian_military_smg_heads", xmodelalias\alias_russian_military_smg_heads::main() );
	self.voice = "shadowcompany";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_russian_military_smg_a_woodland");
	codescripts\character::precacheModelArray(xmodelalias\alias_russian_military_smg_heads::main());
}
