// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_def_mesh_soldier_a");
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("fullbody_def_mesh_soldier_a");
}
