// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_assault_b_woodland");
	codescripts\character::attachHead( "alias_russian_military_assaultb_heads", xmodelalias\alias_russian_military_assaultb_heads::main() );
	self.voice = "russian";
	self SetClothType("cloth");
}

precache()
{
	precacheModel("body_russian_military_assault_b_woodland");
	codescripts\character::precacheModelArray(xmodelalias\alias_russian_military_assaultb_heads::main());
}
