// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_opforce_ghillie_woodland_sniper");
	self attach("head_op_sniper_ghillie_forest", "", true);
	self.headModel = "head_op_sniper_ghillie_forest";
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_opforce_ghillie_woodland_sniper");
	precacheModel("head_op_sniper_ghillie_forest");
}
