// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_lmg_a");
	codescripts\character::attachHead( "alias_russian_military_lmg_heads", xmodelalias\alias_russian_military_lmg_heads::main() );
	self.voice = "russian";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("body_russian_military_lmg_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_russian_military_lmg_heads::main());
}
