// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_keegan_africa_assault_a");
	self.voice = "taskforce";
	self SetClothType("vestheavy");
}

precache()
{
	precacheModel("fullbody_keegan_africa_assault_a");
}
