// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_rpg_a_arctic");
	codescripts\character::attachHead( "test_alias_oilrocks_heads", xmodelalias\test_alias_oilrocks_heads::main() );
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_russian_military_rpg_a_arctic");
	codescripts\character::precacheModelArray(xmodelalias\test_alias_oilrocks_heads::main());
}
