// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "toy_generator_on", destructible_scripts\toy_generator_on::main );
	common_scripts\utility::add_destructible_type_function( "toy_trashbin_02", destructible_scripts\toy_trashbin_02::main );
	maps\animated_models\com_roofvent2::main();
}
