// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "toy_firehydrant", destructible_scripts\toy_firehydrant::main );
	common_scripts\utility::add_destructible_type_function( "toy_trashbin_01", destructible_scripts\toy_trashbin_01::main );
}
