// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "toy_filecabinet", destructible_scripts\toy_filecabinet::main );
	common_scripts\utility::add_destructible_type_function( "toy_locker_double", destructible_scripts\toy_locker_double::main );
	common_scripts\utility::add_destructible_type_function( "toy_trashbin_02", destructible_scripts\toy_trashbin_02::main );
}
