// _createart generated.  modify at your own risk. 
main()
{
	ent = maps\mp\_art::create_vision_set_fog( "mp_frag" );
	ent.startDist = 1500;
	ent.halfwayDist = 6145;
	ent.red = 0.8;
	ent.green = 0.88;
	ent.blue = 1;
	ent.maxOpacity = 0.25;
	ent.transitionTime = 0;
	ent.sunFogEnabled = 1;
	ent.sunRed = 1;
	ent.sunGreen = 1;
	ent.sunBlue = 0.94;
	ent.sunDir = (0.76, 0.38, 0.51);
	ent.sunBeginFadeAngle = 0;
	ent.sunEndFadeAngle = 100;
	ent.normalFogScale = 1.063;
	ent.HDROverride = "mp_frag_HDR";
	ent.skyFogIntensity = 1;
	ent.skyFogMinAngle = 60;
	ent.skyFogMaxAngle = 85;

	ent = maps\mp\_art::create_vision_set_fog( "mp_frag_interior" );
	ent.startDist = 1500;
	ent.halfwayDist = 6145;
	ent.red = 0.8;
	ent.green = 0.88;
	ent.blue = 1;
	ent.maxOpacity = 0.25;
	ent.transitionTime = 0;
	ent.sunFogEnabled = 1;
	ent.sunRed = 1;
	ent.sunGreen = 1;
	ent.sunBlue = 0.94;
	ent.sunDir = (0.76, 0.38, 0.51);
	ent.sunBeginFadeAngle = 0;
	ent.sunEndFadeAngle = 100;
	ent.normalFogScale = 1.063;
	ent.HDROverride = "mp_frag_interior_HDR";
	ent.skyFogIntensity = 1;
	ent.skyFogMinAngle = 60;
	ent.skyFogMaxAngle = 85;

	ent = maps\mp\_art::create_vision_set_fog( "mp_frag_transition" );
	ent.startDist = 1500;
	ent.halfwayDist = 6145;
	ent.red = 0.8;
	ent.green = 0.88;
	ent.blue = 1;
	ent.maxOpacity = 0.25;
	ent.transitionTime = 0;
	ent.sunFogEnabled = 1;
	ent.sunRed = 1;
	ent.sunGreen = 1;
	ent.sunBlue = 0.94;
	ent.sunDir = (0.76, 0.38, 0.51);
	ent.sunBeginFadeAngle = 0;
	ent.sunEndFadeAngle = 100;
	ent.normalFogScale = 1.063;
	ent.skyFogIntensity = 0;
	ent.skyFogMinAngle = 0;
	ent.skyFogMaxAngle = 0;

	ent = maps\mp\_art::create_vision_set_fog( "mp_frag_HDR" );
	ent.startDist = 1500;
	ent.halfwayDist = 6145;
	ent.red = 0.8;
	ent.green = 0.88;
	ent.blue = 1;
	ent.HDRColorIntensity = 1;
	ent.maxOpacity = 0.25;
	ent.transitionTime = 0;
	ent.sunFogEnabled = 1;
	ent.sunRed = 1;
	ent.sunGreen = 1;
	ent.sunBlue = 0.94;
	ent.HDRSunColorIntensity = 1.06;
	ent.sunDir = (0.76, 0.38, 0.51);
	ent.sunBeginFadeAngle = 0;
	ent.sunEndFadeAngle = 100;
	ent.normalFogScale = 1;
	ent.skyFogIntensity = 1;
	ent.skyFogMinAngle = 60;
	ent.skyFogMaxAngle = 85;
	
	ent = maps\mp\_art::create_vision_set_fog( "mp_frag_interior_HDR" );
	ent.startDist = 1500;
	ent.halfwayDist = 6145;
	ent.red = 0.8;
	ent.green = 0.88;
	ent.blue = 1;
	ent.HDRColorIntensity = 1;
	ent.maxOpacity = 0.25;
	ent.transitionTime = 0;
	ent.sunFogEnabled = 1;
	ent.sunRed = 1;
	ent.sunGreen = 1;
	ent.sunBlue = 0.94;
	ent.HDRSunColorIntensity = 1.06;
	ent.sunDir = (0.76, 0.38, 0.51);
	ent.sunBeginFadeAngle = 0;
	ent.sunEndFadeAngle = 100;
	ent.normalFogScale = 1;
	ent.skyFogIntensity = 1;
	ent.skyFogMinAngle = 60;
	ent.skyFogMaxAngle = 85;


	//maps\mp\_art::vision_set_fog_changes( "mp_fog", 0 );
}
