// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "toy_filecabinet", destructible_scripts\toy_filecabinet::main );
	common_scripts\utility::add_destructible_type_function( "toy_firehydrant", destructible_scripts\toy_firehydrant::main );
	common_scripts\utility::add_destructible_type_function( "toy_newspaper_stand_blue", destructible_scripts\toy_newspaper_stand_blue::main );
	common_scripts\utility::add_destructible_type_function( "toy_newspaper_stand_red", destructible_scripts\toy_newspaper_stand_red::main );
	common_scripts\utility::add_destructible_type_function( "toy_parkingmeter", destructible_scripts\toy_parkingmeter::main );
}
