// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\interactive_models\parakeets::main();
	vehicle_scripts\aas_72x::main( "vehicle_aas_72x", undefined, "script_vehicle_aas72x" );
	vehicle_scripts\hind::main( "vehicle_battle_hind", "hind_battle", "script_vehicle_hind_battle" );
	vehicle_scripts\_soc_r::main( "vehicle_soc_r", undefined, "script_vehicle_soc_r" );
	vehicle_scripts\_stryker50cal::main( "vehicle_stryker_config2", "stryker50cal_notrophy", "script_vehicle_stryker50cal_notrophy" );
}
