// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "electrical_transformer_large", destructible_scripts\electrical_transformer_large::main );
	common_scripts\utility::add_destructible_type_function( "toy_propane_tank02_small", destructible_scripts\toy_propane_tank02_small::main );
	common_scripts\utility::add_destructible_type_function( "toy_sp_panel_box", destructible_scripts\toy_sp_panel_box::main );
	common_scripts\utility::add_destructible_type_function( "toy_transformer_small01", destructible_scripts\toy_transformer_small01::main );
}
