// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\utility::add_destructible_type_function( "toy_sp_panel_box", destructible_scripts\toy_sp_panel_box::main );
	vehicle_scripts\_jeep_rubicon_payback::main( "vehicle_jeep_rubicon",undefined, "script_vehicle_jeep_rubicon_payback" );
}
