// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_jeep_rubicon_payback::main( "vehicle_jeep_rubicon",undefined, "script_vehicle_jeep_rubicon_payback" );
}
