// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_gallery_russian_military (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_russian_military_assault_a"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "axis";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 100;
	self.secondaryweapon = "";
	self.sidearm = "beretta";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 256.000000, 0.000000 );
		self setEngagementMaxDist( 768.000000, 1024.000000 );
	}

	self.weapon = "ak47";

	switch( codescripts\character::get_random_character(24) )
	{
	case 0:
		character\character_russian_military_assault_a::main();
		break;
	case 1:
		character\character_russian_military_assault_a_a::main();
		break;
	case 2:
		character\character_russian_military_assault_a_s::main();
		break;
	case 3:
		character\character_russian_military_assault_a_w::main();
		break;
	case 4:
		character\character_russian_military_assault_b::main();
		break;
	case 5:
		character\character_russian_military_assault_b_a::main();
		break;
	case 6:
		character\character_russian_military_assault_b_s::main();
		break;
	case 7:
		character\character_russian_military_assault_b_w::main();
		break;
	case 8:
		character\character_russian_military_lmg_a::main();
		break;
	case 9:
		character\character_russian_military_lmg_a_a::main();
		break;
	case 10:
		character\character_russian_military_lmg_a_s::main();
		break;
	case 11:
		character\character_russian_military_lmg_a_w::main();
		break;
	case 12:
		character\character_russian_military_rpg_a::main();
		break;
	case 13:
		character\character_russian_military_rpg_a_a::main();
		break;
	case 14:
		character\character_russian_military_rpg_a_s::main();
		break;
	case 15:
		character\character_russian_military_rpg_a_w::main();
		break;
	case 16:
		character\character_russian_military_shgn_a::main();
		break;
	case 17:
		character\character_russian_military_shgn_a_a::main();
		break;
	case 18:
		character\character_russian_military_shgn_a_s::main();
		break;
	case 19:
		character\character_russian_military_shgn_a_w::main();
		break;
	case 20:
		character\character_russian_military_smg_a::main();
		break;
	case 21:
		character\character_russian_military_smg_a_a::main();
		break;
	case 22:
		character\character_russian_military_smg_a_s::main();
		break;
	case 23:
		character\character_russian_military_smg_a_w::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_russian_military_assault_a::precache();
	character\character_russian_military_assault_a_a::precache();
	character\character_russian_military_assault_a_s::precache();
	character\character_russian_military_assault_a_w::precache();
	character\character_russian_military_assault_b::precache();
	character\character_russian_military_assault_b_a::precache();
	character\character_russian_military_assault_b_s::precache();
	character\character_russian_military_assault_b_w::precache();
	character\character_russian_military_lmg_a::precache();
	character\character_russian_military_lmg_a_a::precache();
	character\character_russian_military_lmg_a_s::precache();
	character\character_russian_military_lmg_a_w::precache();
	character\character_russian_military_rpg_a::precache();
	character\character_russian_military_rpg_a_a::precache();
	character\character_russian_military_rpg_a_s::precache();
	character\character_russian_military_rpg_a_w::precache();
	character\character_russian_military_shgn_a::precache();
	character\character_russian_military_shgn_a_a::precache();
	character\character_russian_military_shgn_a_s::precache();
	character\character_russian_military_shgn_a_w::precache();
	character\character_russian_military_smg_a::precache();
	character\character_russian_military_smg_a_a::precache();
	character\character_russian_military_smg_a_s::precache();
	character\character_russian_military_smg_a_w::precache();

	precacheItem("ak47");
	precacheItem("beretta");
	precacheItem("fraggrenade");
}
