// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_test_enemy_shark_dog (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="fullbody_prototype_shark_a"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "animals.atr";
	self.additionalAssets = "common_sharks.csv";
	self.team = "axis";
	self.type = "dog";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 200;
	self.secondaryweapon = "dog_bite";
	self.sidearm = "";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 256.000000, 0.000000 );
		self setEngagementMaxDist( 768.000000, 1024.000000 );
	}

	self.weapon = "dog_bite";

	character\character_enemy_shark::main();
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_enemy_shark::precache();

	precacheItem("dog_bite");
	precacheItem("dog_bite");
	precacheItem("fraggrenade");

	//----------------
	animscripts\dog\dog_init::initDogAnimations();
	//----------------
}
