// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_test_enemy_arctic_rpg (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_opforce_arctic_smg"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "weapon_rpg_player.csv";
	self.team = "axis";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 150;
	self.secondaryweapon = "ak47_arctic_reflex";
	self.sidearm = "usp";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 0.000000, 0.000000 );
		self setEngagementMaxDist( 280.000000, 400.000000 );
	}

	self.weapon = "rpg";

	character\character_russian_military_rpg_a_s::main();
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_russian_military_rpg_a_s::precache();

	precacheItem("rpg");
	precacheItem("ak47_arctic_reflex");
	precacheItem("usp");
	precacheItem("fraggrenade");
}
