// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_test_enemy_opforce_fed_lmg (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_venezuela_army_assault_a"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "axis";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 150;
	self.secondaryweapon = "";
	self.sidearm = "p226";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 128.000000, 0.000000 );
		self setEngagementMaxDist( 1024.000000, 1250.000000 );
	}

	switch( codescripts\character::get_random_weapon(2) )
	{
	case 0:
		self.weapon = "pecheneg";
		break;
	case 1:
		self.weapon = "pecheneg_reflex";
		break;
	}

	character\character_venezuela_army_assault_a::main();
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_venezuela_army_assault_a::precache();

	precacheItem("pecheneg");
	precacheItem("pecheneg_reflex");
	precacheItem("p226");
	precacheItem("fraggrenade");
}
