// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_test_enemy_venezuela_army_FAD (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_venezuela_army_assault_a"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "axis";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 150;
	self.secondaryweapon = "";
	self.sidearm = "p226";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 256.000000, 0.000000 );
		self setEngagementMaxDist( 768.000000, 1024.000000 );
	}

	switch( codescripts\character::get_random_weapon(4) )
	{
	case 0:
		self.weapon = "ak12";
		break;
	case 1:
		self.weapon = "ak12+reflex_sp";
		break;
	case 2:
		self.weapon = "ak12+eotech_sp";
		break;
	case 3:
		self.weapon = "ak12+acog_sp";
		break;
	}

	switch( codescripts\character::get_random_character(2) )
	{
	case 0:
		character\character_venezuela_army_assault_a::main();
		break;
	case 1:
		character\character_venezuela_army_smg_a::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_venezuela_army_assault_a::precache();
	character\character_venezuela_army_smg_a::precache();

	precacheItem("ak12");
	precacheItem("ak12+reflex_sp");
	precacheItem("ak12+eotech_sp");
	precacheItem("ak12+acog_sp");
	precacheItem("p226");
	precacheItem("fraggrenade");
}
