// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_test_ally_us_rangers_urban_ARX160 (0.0 0.25 1.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_us_rangers_assault_a_urban"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "allies";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 100;
	self.secondaryweapon = "";
	self.sidearm = "p226";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 256.000000, 0.000000 );
		self setEngagementMaxDist( 768.000000, 1024.000000 );
	}

	switch( codescripts\character::get_random_weapon(3) )
	{
	case 0:
		self.weapon = "cz805bren";
		break;
	case 1:
		self.weapon = "cz805bren+acog_sp";
		break;
	case 2:
		self.weapon = "cz805bren+reflex_sp";
		break;
	}

	switch( codescripts\character::get_random_character(3) )
	{
	case 0:
		character\character_us_rangers_assault_a_urban::main();
		break;
	case 1:
		character\character_us_rangers_lmg_a_urban::main();
		break;
	case 2:
		character\character_us_rangers_shotgun_a_urban::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("allies");
}

precache()
{
	character\character_us_rangers_assault_a_urban::precache();
	character\character_us_rangers_lmg_a_urban::precache();
	character\character_us_rangers_shotgun_a_urban::precache();

	precacheItem("cz805bren");
	precacheItem("cz805bren+acog_sp");
	precacheItem("cz805bren+reflex_sp");
	precacheItem("p226");
	precacheItem("fraggrenade");
}
