// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_test_enemy_arctic_worker_ar (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_work_civ_male_a"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "axis";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 150;
	self.secondaryweapon = "";
	self.sidearm = "usp";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 128.000000, 0.000000 );
		self setEngagementMaxDist( 512.000000, 1024.000000 );
	}

	switch( codescripts\character::get_random_weapon(2) )
	{
	case 0:
		self.weapon = "ak47_arctic";
		break;
	case 1:
		self.weapon = "ak47_arctic_reflex";
		break;
	}

	switch( codescripts\character::get_random_character(4) )
	{
	case 0:
		character\character_chemwar_russian_assault_d::main();
		break;
	case 1:
		character\character_chemwar_russian_assault_dd::main();
		break;
	case 2:
		character\character_chemwar_russian_assault_e::main();
		break;
	case 3:
		character\character_chemwar_russian_assault_ee::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_chemwar_russian_assault_d::precache();
	character\character_chemwar_russian_assault_dd::precache();
	character\character_chemwar_russian_assault_e::precache();
	character\character_chemwar_russian_assault_ee::precache();

	precacheItem("ak47_arctic");
	precacheItem("ak47_arctic_reflex");
	precacheItem("usp");
	precacheItem("fraggrenade");
}
